# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogu_3.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_grade = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_grade.sizePolicy().hasHeightForWidth())
        self.comboBox_grade.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.comboBox_grade.setFont(font)
        self.comboBox_grade.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_grade.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_grade.setObjectName("comboBox_grade")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.verticalLayout.addWidget(self.comboBox_grade, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox_Ok_pilot = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox_Ok_pilot.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox_Ok_pilot.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Ok_pilot.setObjectName("buttonBox_Ok_pilot")
        self.gridLayout.addWidget(self.buttonBox_Ok_pilot, 0, 1, 1, 1)
        self.label.setBuddy(self.comboBox_grade)
        self.label_2.setBuddy(self.lineEdit_2)
        self.label_3.setBuddy(self.lineEdit_3)

        self.retranslateUi(Dialog)
        self.comboBox_grade.setCurrentIndex(3)
        self.buttonBox_Ok_pilot.accepted.connect(Dialog.accept)
        self.buttonBox_Ok_pilot.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox_grade, self.lineEdit_2)
        Dialog.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.buttonBox_Ok_pilot)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "GRADE"))
        self.comboBox_grade.setItemText(0, _translate("Dialog", "ASPIRANT"))
        self.comboBox_grade.setItemText(1, _translate("Dialog", "SOUS-LIEUTENANT"))
        self.comboBox_grade.setItemText(2, _translate("Dialog", "LIEUTENANT"))
        self.comboBox_grade.setItemText(3, _translate("Dialog", "CAPITAINE"))
        self.comboBox_grade.setItemText(4, _translate("Dialog", "COMMANDANT"))
        self.comboBox_grade.setItemText(5, _translate("Dialog", "LIEUTENANT-COLONEL"))
        self.comboBox_grade.setItemText(6, _translate("Dialog", "COLONEL"))
        self.label_2.setText(_translate("Dialog", "PRENOM"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "FRANCOIS"))
        self.label_3.setText(_translate("Dialog", "NOM"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "PIGNON"))

