# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtSqlTry.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 577)
        self.lineEditPilote = QtWidgets.QLineEdit(Form)
        self.lineEditPilote.setGeometry(QtCore.QRect(30, 20, 146, 29))
        self.lineEditPilote.setObjectName("lineEditPilote")
        self.dateTimeEdit_1 = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit_1.setGeometry(QtCore.QRect(30, 90, 194, 24))
        self.dateTimeEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit_1.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 12, 31), QtCore.QTime(12, 0, 0)))
        self.dateTimeEdit_1.setDate(QtCore.QDate(1999, 12, 31))
        self.dateTimeEdit_1.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit_1.setDisplayFormat("yyyy/MM/dd HH:mm")
        self.dateTimeEdit_1.setCalendarPopup(True)
        self.dateTimeEdit_1.setCurrentSectionIndex(0)
        self.dateTimeEdit_1.setTimeSpec(QtCore.Qt.UTC)
        self.dateTimeEdit_1.setObjectName("dateTimeEdit_1")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(30, 120, 194, 24))
        self.dateTimeEdit_2.setWrapping(True)
        self.dateTimeEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(2, 0, 0)))
        self.dateTimeEdit_2.setDisplayFormat("yyyy/MM/dd HH:mm")
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 490, 171, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_total = QtWidgets.QLabel(self.layoutWidget)
        self.label_total.setObjectName("label_total")
        self.horizontalLayout.addWidget(self.label_total)
        self.lineEdit_immat = QtWidgets.QLineEdit(Form)
        self.lineEdit_immat.setGeometry(QtCore.QRect(50, 150, 113, 21))
        self.lineEdit_immat.setObjectName("lineEdit_immat")
        self.lineEdit_ac_type = QtWidgets.QLineEdit(Form)
        self.lineEdit_ac_type.setGeometry(QtCore.QRect(190, 150, 113, 21))
        self.lineEdit_ac_type.setObjectName("lineEdit_ac_type")
        self.lineEdit_puisance = QtWidgets.QLineEdit(Form)
        self.lineEdit_puisance.setGeometry(QtCore.QRect(340, 150, 113, 21))
        self.lineEdit_puisance.setObjectName("lineEdit_puisance")
        self.lineEdit_aircraft = QtWidgets.QLineEdit(Form)
        self.lineEdit_aircraft.setGeometry(QtCore.QRect(30, 60, 141, 21))
        self.lineEdit_aircraft.setObjectName("lineEdit_aircraft")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(210, 30, 432, 26))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.dateEdit = QtWidgets.QDateEdit(self.splitter_2)
        self.dateEdit.setTime(QtCore.QTime(0, 0, 0))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.splitter_2)
        self.dateEdit_2.setTime(QtCore.QTime(0, 0, 0))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.comboBox = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_print = QtWidgets.QPushButton(Form)
        self.pushButton_print.setGeometry(QtCore.QRect(500, 150, 110, 32))
        self.pushButton_print.setObjectName("pushButton_print")
        self.tableView2 = QtWidgets.QTableView(Form)
        self.tableView2.setGeometry(QtCore.QRect(340, 200, 451, 192))
        self.tableView2.setObjectName("tableView2")
        self.tableView1 = QtWidgets.QTableView(Form)
        self.tableView1.setGeometry(QtCore.QRect(30, 200, 256, 192))
        self.tableView1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView1.setAlternatingRowColors(True)
        self.tableView1.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableView1.setSortingEnabled(True)
        self.tableView1.setObjectName("tableView1")
        self.tableView1.horizontalHeader().setVisible(True)
        self.tableView1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView1.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 442, 392, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.Calcul = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Calcul.setObjectName("Calcul")
        self.horizontalLayout_2.addWidget(self.Calcul)
        self.pushButton_effacer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_effacer.setToolTip("")
        self.pushButton_effacer.setWhatsThis("")
        self.pushButton_effacer.setObjectName("pushButton_effacer")
        self.horizontalLayout_2.addWidget(self.pushButton_effacer)
        self.calcul_temps = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.calcul_temps.setToolTip("")
        self.calcul_temps.setObjectName("calcul_temps")
        self.horizontalLayout_2.addWidget(self.calcul_temps)
        self.pushButton_filter = QtWidgets.QPushButton(Form)
        self.pushButton_filter.setGeometry(QtCore.QRect(440, 440, 110, 32))
        self.pushButton_filter.setObjectName("pushButton_filter")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TOTAL :"))
        self.label_total.setText(_translate("Form", "TextLabel"))
        self.lineEdit_immat.setPlaceholderText(_translate("Form", "immat"))
        self.lineEdit_ac_type.setPlaceholderText(_translate("Form", "ac type"))
        self.lineEdit_puisance.setPlaceholderText(_translate("Form", "puissance"))
        self.dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.dateEdit_2.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.pushButton_print.setText(_translate("Form", "print"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.Calcul.setText(_translate("Form", "Calcul"))
        self.pushButton_effacer.setText(_translate("Form", "Effacer"))
        self.calcul_temps.setText(_translate("Form", "calculTemps"))
        self.pushButton_filter.setText(_translate("Form", "Filter"))

