# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TabView.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(844, 560)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Qtable = QtWidgets.QTabWidget(Dialog)
        self.Qtable.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Qtable.setMovable(True)
        self.Qtable.setObjectName("Qtable")
        self.Insertion = QtWidgets.QWidget()
        self.Insertion.setObjectName("Insertion")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Insertion)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.Insertion)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_heures_total = QtWidgets.QLineEdit(self.Insertion)
        self.lineEdit_heures_total.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_heures_total.setObjectName("lineEdit_heures_total")
        self.horizontalLayout_2.addWidget(self.lineEdit_heures_total)
        self.label = QtWidgets.QLabel(self.Insertion)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Insertion)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Insertion)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_observations = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_observations.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_observations.setObjectName("lineEdit_observations")
        self.gridLayout_2.addWidget(self.lineEdit_observations, 9, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_3)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 3, 0, 1, 1)
        self.comboBox_avion = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_avion.setObjectName("comboBox_avion")
        self.gridLayout_2.addWidget(self.comboBox_avion, 2, 0, 1, 1)
        self.comboBox_pilot2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_pilot2.setObjectName("comboBox_pilot2")
        self.gridLayout_2.addWidget(self.comboBox_pilot2, 1, 0, 1, 1)
        self.comboBox_pilot1 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_pilot1.setObjectName("comboBox_pilot1")
        self.gridLayout_2.addWidget(self.comboBox_pilot1, 0, 0, 1, 1)
        self.lineEdit_pax2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_pax2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pax2.setObjectName("lineEdit_pax2")
        self.gridLayout_2.addWidget(self.lineEdit_pax2, 6, 0, 1, 1)
        self.lineEdit_pax1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_pax1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pax1.setObjectName("lineEdit_pax1")
        self.gridLayout_2.addWidget(self.lineEdit_pax1, 5, 0, 1, 1)
        self.lineEdit_mission = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_mission.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mission.setObjectName("lineEdit_mission")
        self.gridLayout_2.addWidget(self.lineEdit_mission, 8, 0, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox_3)
        self.dateTimeEdit_2.setDisplayFormat("yyyy-MM-dd HH:mm")
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setTimeSpec(QtCore.Qt.UTC)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_2.addWidget(self.dateTimeEdit_2, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Insertion)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_pilote = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_pilote.setObjectName("comboBox_pilote")
        self.gridLayout.addWidget(self.comboBox_pilote, 1, 2, 1, 1)
        self.tableView_3 = QtWidgets.QTableView(self.groupBox_4)
        self.tableView_3.setObjectName("tableView_3")
        self.gridLayout.addWidget(self.tableView_3, 0, 0, 1, 4)
        self.comboBox_pilote2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_pilote2.setObjectName("comboBox_pilote2")
        self.gridLayout.addWidget(self.comboBox_pilote2, 1, 3, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_4)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.dateEdit.setDate(QtCore.QDate(2017, 12, 22))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7999, 12, 30), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox_4)
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 2, 2, 1, 1)
        self.comboBox_sel_ac = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_sel_ac.setObjectName("comboBox_sel_ac")
        self.gridLayout.addWidget(self.comboBox_sel_ac, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 3, 1, 1)
        self.tableView = QtWidgets.QTableView(self.Insertion)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 2, 0, 1, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insert_data = QtWidgets.QPushButton(self.Insertion)
        self.insert_data.setObjectName("insert_data")
        self.horizontalLayout.addWidget(self.insert_data)
        self.Effacer = QtWidgets.QPushButton(self.Insertion)
        self.Effacer.setObjectName("Effacer")
        self.horizontalLayout.addWidget(self.Effacer)
        self.calculer = QtWidgets.QPushButton(self.Insertion)
        self.calculer.setObjectName("calculer")
        self.horizontalLayout.addWidget(self.calculer)
        self.enter_new_AC = QtWidgets.QPushButton(self.Insertion)
        self.enter_new_AC.setObjectName("enter_new_AC")
        self.horizontalLayout.addWidget(self.enter_new_AC)
        self.enter_new_pilot = QtWidgets.QPushButton(self.Insertion)
        self.enter_new_pilot.setObjectName("enter_new_pilot")
        self.horizontalLayout.addWidget(self.enter_new_pilot)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 4)
        self.Qtable.addTab(self.Insertion, "")
        self.Limites = QtWidgets.QWidget()
        self.Limites.setObjectName("Limites")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Limites)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Limites)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableView_limites = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_limites.setObjectName("tableView_limites")
        self.gridLayout_9.addWidget(self.tableView_limites, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.Limites)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.dateEdit_lim_vsa = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_lim_vsa.setCalendarPopup(True)
        self.dateEdit_lim_vsa.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_lim_vsa.setObjectName("dateEdit_lim_vsa")
        self.gridLayout_6.addWidget(self.dateEdit_lim_vsa, 5, 1, 1, 1)
        self.dateEdit_lim_cempn = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_lim_cempn.setCalendarPopup(True)
        self.dateEdit_lim_cempn.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_lim_cempn.setObjectName("dateEdit_lim_cempn")
        self.gridLayout_6.addWidget(self.dateEdit_lim_cempn, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 2, 1, 1)
        self.dateEdit_7 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_7.setCalendarPopup(True)
        self.dateEdit_7.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.gridLayout_6.addWidget(self.dateEdit_7, 5, 2, 1, 1)
        self.dateEdit_lim_license = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_lim_license.setCalendarPopup(True)
        self.dateEdit_lim_license.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_lim_license.setObjectName("dateEdit_lim_license")
        self.gridLayout_6.addWidget(self.dateEdit_lim_license, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(494, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 2, 1, 1, 1)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_3.setDisplayFormat("yyyy-MM-dd")
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.gridLayout_6.addWidget(self.dateEdit_3, 7, 3, 1, 1)
        self.lineEdit_lim_pilot = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_lim_pilot.setMaximumSize(QtCore.QSize(494, 16777215))
        self.lineEdit_lim_pilot.setObjectName("lineEdit_lim_pilot")
        self.gridLayout_6.addWidget(self.lineEdit_lim_pilot, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 4, 3, 1, 1)
        self.pushButton_lim_inserer = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_lim_inserer.setObjectName("pushButton_lim_inserer")
        self.gridLayout_6.addWidget(self.pushButton_lim_inserer, 8, 1, 1, 1)
        self.dateEdit_6 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_6.setCalendarPopup(True)
        self.dateEdit_6.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.gridLayout_6.addWidget(self.dateEdit_6, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(494, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(494, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 4, 2, 1, 1)
        self.dateEdit_9 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_9.setCalendarPopup(True)
        self.dateEdit_9.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_9.setObjectName("dateEdit_9")
        self.gridLayout_6.addWidget(self.dateEdit_9, 3, 3, 1, 1)
        self.dateEdit_10 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_10.setCalendarPopup(True)
        self.dateEdit_10.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_10.setObjectName("dateEdit_10")
        self.gridLayout_6.addWidget(self.dateEdit_10, 5, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 6, 2, 1, 1)
        self.dateEdit_8 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_8.setCalendarPopup(True)
        self.dateEdit_8.setTimeSpec(QtCore.Qt.UTC)
        self.dateEdit_8.setObjectName("dateEdit_8")
        self.gridLayout_6.addWidget(self.dateEdit_8, 7, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 6, 3, 1, 1)
        self.pushButton_lim_supprimer = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_lim_supprimer.setObjectName("pushButton_lim_supprimer")
        self.gridLayout_6.addWidget(self.pushButton_lim_supprimer, 8, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.Qtable.addTab(self.Limites, "")
        self.RECAP = QtWidgets.QWidget()
        self.RECAP.setObjectName("RECAP")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.RECAP)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.RECAP)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableView_2 = QtWidgets.QTableView(self.splitter)
        self.tableView_2.setObjectName("tableView_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.autre_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.autre_btn.setObjectName("autre_btn")
        self.horizontalLayout_3.addWidget(self.autre_btn)
        self.calculer_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.calculer_btn.setObjectName("calculer_btn")
        self.horizontalLayout_3.addWidget(self.calculer_btn)
        self.inserer_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.inserer_btn.setObjectName("inserer_btn")
        self.horizontalLayout_3.addWidget(self.inserer_btn)
        self.effacer_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.effacer_btn.setObjectName("effacer_btn")
        self.horizontalLayout_3.addWidget(self.effacer_btn)
        self.gridLayout_4.addWidget(self.splitter, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.RECAP)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.Qtable.addTab(self.RECAP, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textEdit = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_5.addWidget(self.textEdit, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_imprimer = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_imprimer.setObjectName("pushButton_imprimer")
        self.horizontalLayout_7.addWidget(self.pushButton_imprimer)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.tab_6)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.Qtable.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.Qtable)
        self.label_2.setBuddy(self.lineEdit_heures_total)
        self.label.setBuddy(self.lineEdit_3)
        self.label_4.setBuddy(self.lineEdit_lim_pilot)

        self.retranslateUi(Dialog)
        self.Qtable.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_pax1, self.lineEdit_pax2)
        Dialog.setTabOrder(self.lineEdit_pax2, self.insert_data)
        Dialog.setTabOrder(self.insert_data, self.Effacer)
        Dialog.setTabOrder(self.Effacer, self.calculer)
        Dialog.setTabOrder(self.calculer, self.enter_new_AC)
        Dialog.setTabOrder(self.enter_new_AC, self.enter_new_pilot)
        Dialog.setTabOrder(self.enter_new_pilot, self.tableView_3)
        Dialog.setTabOrder(self.tableView_3, self.dateEdit)
        Dialog.setTabOrder(self.dateEdit, self.dateEdit_2)
        Dialog.setTabOrder(self.dateEdit_2, self.comboBox_pilote)
        Dialog.setTabOrder(self.comboBox_pilote, self.comboBox_pilote2)
        Dialog.setTabOrder(self.comboBox_pilote2, self.lineEdit_2)
        Dialog.setTabOrder(self.lineEdit_2, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_4, self.tableView)
        Dialog.setTabOrder(self.tableView, self.lineEdit_heures_total)
        Dialog.setTabOrder(self.lineEdit_heures_total, self.tableView_limites)
        Dialog.setTabOrder(self.tableView_limites, self.effacer_btn)
        Dialog.setTabOrder(self.effacer_btn, self.tableView_2)
        Dialog.setTabOrder(self.tableView_2, self.autre_btn)
        Dialog.setTabOrder(self.autre_btn, self.inserer_btn)
        Dialog.setTabOrder(self.inserer_btn, self.calculer_btn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Master Window"))
        Dialog.setWhatsThis(_translate("Dialog", "Inserer Appareil"))
        self.label_2.setText(_translate("Dialog", "HEURES TOTALES"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.groupBox_3.setTitle(_translate("Dialog", "INSERTION"))
        self.lineEdit_observations.setPlaceholderText(_translate("Dialog", "Observations"))
        self.dateTimeEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd HH:mm"))
        self.lineEdit_pax2.setPlaceholderText(_translate("Dialog", "pax 2"))
        self.lineEdit_pax1.setPlaceholderText(_translate("Dialog", "pax 1"))
        self.lineEdit_mission.setPlaceholderText(_translate("Dialog", "Mission"))
        self.groupBox_4.setTitle(_translate("Dialog", "SELECTION"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.dateEdit_2.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.insert_data.setText(_translate("Dialog", "Inserer"))
        self.Effacer.setText(_translate("Dialog", "Effacer"))
        self.Effacer.setShortcut(_translate("Dialog", "Backspace"))
        self.calculer.setText(_translate("Dialog", "Calculer"))
        self.enter_new_AC.setText(_translate("Dialog", "Appareil"))
        self.enter_new_pilot.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-style:italic;\">Permet de creer un nouveau Pilote et de l\'inserer dans la base de donnée</span></p></body></html>"))
        self.enter_new_pilot.setText(_translate("Dialog", "Pilote"))
        self.Qtable.setTabText(self.Qtable.indexOf(self.Insertion), _translate("Dialog", "INSERTION"))
        self.groupBox_2.setTitle(_translate("Dialog", "GroupBox"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.dateEdit_lim_vsa.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.dateEdit_lim_cempn.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_11.setText(_translate("Dialog", "TextLabel"))
        self.label_8.setText(_translate("Dialog", "TextLabel"))
        self.dateEdit_7.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.dateEdit_lim_license.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_5.setText(_translate("Dialog", "CEMPN"))
        self.label_12.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_lim_inserer.setText(_translate("Dialog", "INSERER"))
        self.dateEdit_6.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_7.setText(_translate("Dialog", "LICENSE"))
        self.label_4.setText(_translate("Dialog", "Pilote"))
        self.label_6.setText(_translate("Dialog", "VSA"))
        self.label_9.setText(_translate("Dialog", "TextLabel"))
        self.dateEdit_9.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.dateEdit_10.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_10.setText(_translate("Dialog", "TextLabel"))
        self.dateEdit_8.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_13.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_lim_supprimer.setText(_translate("Dialog", "SUPPRIMER"))
        self.Qtable.setTabText(self.Qtable.indexOf(self.Limites), _translate("Dialog", "LIMITES"))
        self.autre_btn.setText(_translate("Dialog", "autre"))
        self.calculer_btn.setText(_translate("Dialog", "calculer"))
        self.inserer_btn.setText(_translate("Dialog", "inserer"))
        self.effacer_btn.setText(_translate("Dialog", "effacer"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.Qtable.setTabText(self.Qtable.indexOf(self.RECAP), _translate("Dialog", "RECAP"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_imprimer.setText(_translate("Dialog", "IMPRIMER"))
        self.pushButton_3.setText(_translate("Dialog", "PushButton"))
        self.pushButton_2.setText(_translate("Dialog", "PushButton"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.Qtable.setTabText(self.Qtable.indexOf(self.tab_6), _translate("Dialog", "Page"))

